/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jaM3sXANvQb
 */
import Link from "next/link"

export function Component() {
  return (
    <div
      key="1"
      className="bg-gradient-to-r from-[#252135] via-black to-[#201F2F] text-white min-h-screen flex flex-col justify-center items-center"
    >
      <h1 className="text-6xl font-bold mb-2 bg-gradient-to-r from-gray-400 via-gray-500 to-white text-transparent bg-clip-text">
        Le Vinh Khang
      </h1>
      <h2 className="text-4xl font-light mb-4 bg-gradient-to-r from-white via-gray-500 to-gray-900 text-transparent bg-clip-text">
        Developer
      </h2>
      <hr className="border-gray-700 w-full max-w-lg mb-8" />
      <p className="mb-8 text-center max-w-lg text-[#AEB2B6]">
        Hello, I am a student from Vietnam, living in Ho Chi Minh City. I am currently studying at Kien Giang College,
        Faculty of Information Technology. This blog is for documenting my programming journey, running on Amazon
        Hosting. I love learning web technologies, but I often forget, that's why I'm writing this. You can contact me
        via the following form. Have a lucky day!
      </p>
      <hr className="border-gray-700 w-full max-w-lg mb-8" />
      <ul className="list-none space-y-2 text-center">
        <li>
          <Link className="text-[#525355] hover:underline hover:text-[#525355]" href="#">
            GitHub @levinhkhangzz
          </Link>
        </li>
        <li>
          <Link className="text-[#525355] hover:underline hover:text-[#525355]" href="#">
            Email levinhkhang631@gmail.com
          </Link>
        </li>
        <li>
          <Link className="text-[#525355] hover:underline hover:text-[#525355]" href="#">
            Twitter @aedotris
          </Link>
        </li>
        <li>
          <Link className="text-[#525355] hover:underline hover:text-[#525355]" href="#">
            Instagram @williamcachamwri
          </Link>
        </li>
      </ul>
      <footer className="absolute bottom-0 w-full text-center p-4">
        <p className="text-[#AEB2B6] bg-gradient-to-r from-black via-gray-500 to-white text-transparent bg-clip-text font-aquire">
          <span className="text-sm">Made by</span>
          <br />
          <span className="font-bold bg-gradient-to-r from-white to-gray-500 to-white text-transparent bg-clip-text">
            Le Vinh Khang
          </span>
        </p>
      </footer>
    </div>
  )
}
